#!/usr/bin/env bash

## SETUP
  here="`dirname $0`"

  source $here/test_helper
  source $here/../scripts/pair

#1 should set $GIT_AUTHOR_NAME
pair ryalnd &> /dev/null
assert equal "$GIT_AUTHOR_NAME" "Ryland Herrick"

#2 should set $GIT_AUTHOR_EMAIL
pair ryalnd &> /dev/null
assert match "$GIT_AUTHOR_EMAIL" "ryalnd"

#3 should unset $GIT_AUTHOR_NAME
pair -u &> /dev/null
assert blank "$GIT_AUTHOR_NAME"

#4 should unset $GIT_AUTHOR_EMAIL
pair -u &> /dev/null
assert blank "$GIT_AUTHOR_EMAIL"

#5 should use dev@bendyworks.com in the email
pair ryalnd &> /dev/null
assert match "$GIT_AUTHOR_EMAIL" "dev.*bendyworks\.com"

#6 should set multiple usernames in the email
pair ryalnd bendycode &> /dev/null
assert match "$GIT_AUTHOR_EMAIL" "ryalnd"
assert match "$GIT_AUTHOR_EMAIL" "bendycode"

#7 should sort multiple usernames in the email alphabetically
pair ryalnd bendycode &> /dev/null
assert match "$GIT_AUTHOR_EMAIL" "dev\+bendycode\+ryalnd@"

#8 should set multiple names for the author
pair ryalnd bendycode &> /dev/null
assert match "$GIT_AUTHOR_NAME" "Ryland\ Herrick"
assert match "$GIT_AUTHOR_NAME" "Stephen\ Anderson"

#9 should sort author names alphabetically by username
pair ryalnd bendycode &> /dev/null
assert equal "$GIT_AUTHOR_NAME" "Stephen Anderson and Ryland Herrick"

#10 should correctly list more than two authors WITH AN OXFORD COMMA
pair ryalnd bendycode bigtiger &> /dev/null
assert equal "$GIT_AUTHOR_NAME" "Stephen Anderson, Jim Remsik, and Ryland Herrick"

## TEARDOWN
  pair -u &> /dev/null
  echo
