#!/usr/bin/env bash

function assert {
  if [[ $# -lt 2 ]]; then
    echo "Usage: $0 OPERAND [ARGS...]"
  fi

  case $1 in

  == | equal )
    print_result "[[ ! '$2' = '$3' ]]" "FAIL: expected [$2] to equal [$3]"
  ;;

  =~ | match )
    print_result "[[ ! '$2' =~ ${3} ]]" "FAIL: expected [$2] to match [$3]"
  ;;

  blank )
    print_result "[[ -n '$2' ]]" "FAIL: expected [$2] to be blank"
  ;;

  *) echo "Unknown operand [$1]"; exit 1

  esac
}

function print_result {
  if eval $1; then
    echo $2
  else
    echo -n '.'
  fi
}
