#!/usr/bin/env bash

## SETUP
  setup_test_root=$(dirname $BASH_SOURCE)
  source $setup_test_root/../test_helper
  source $setup_test_root/../../setup/pair

  backup_files() {
    [[ -e $HOME/.bash_profile ]] && back_bash=true
    [[ -e $HOME/.pair ]] && back_pair=true

    [[ -n "$back_bash" ]] && mv $HOME/.bash_profile{,.bak}
    [[ -n "$back_pair" ]] && mv $HOME/.pair{,.bak}
    touch $HOME/.bash_profile
  }
  backup_files

  pair_hook="$(pair_hook)"

it "adds to .bash_profile"
  modify_dotfile &> /dev/null
  added_lines="$(cat $HOME/.bash_profile)"
  assert equal "$added_lines" "$pair_hook"

it "is idempotent"
  modify_dotfile &> /dev/null
  added_lines="$(cat $HOME/.bash_profile)"
  assert equal "$added_lines" "$pair_hook"

## TEARDOWN
  [[ -n "$back_bash" ]] && mv $HOME/.bash_profile{.bak,} || rm $HOME/.bash_profile
  [[ -n "$back_pair" ]] && mv $HOME/.pair{.bak,} || rm $HOME/.pair
  echo
  [[ -z "$fail" ]] || exit 1
