#!/usr/bin/env bash

## SETUP
  here=$(dirname $0)
  source $here/../test_helper
  source $here/../../setup/pair

  backup_files() {
    [[ -e $HOME/.bash_profile ]] && backup=true

    [[ -n "$backup" ]] && mv $HOME/.bash_profile{,.bak}
    touch $HOME/.bash_profile
  }
  backup_files

  pair_hook="$(pair_hook)"

it "adds to .bash_profile"
  modify_dotfile &> /dev/null
  added_lines="$(cat $HOME/.bash_profile)"
  assert equal "$added_lines" "$pair_hook"

it "is idempotent"
  modify_dotfile &> /dev/null
  added_lines="$(cat $HOME/.bash_profile)"
  assert equal "$added_lines" "$pair_hook"

## TEARDOWN
  [[ -n "$backup" ]] && mv $HOME/.bash_profile{.bak,} || rm $HOME/.bash_profile
  echo
  [[ -z "$fail" ]] || exit 1
