#!/usr/bin/env bash

function assert {
  if [[ $# -lt 2 ]]; then
    echo "Usage: $0 OPERAND [ARGS...]"
  fi

  case $1 in

  == | equal )
    if [[ ! "$2" = "$3" ]]; then
      echo "FAIL: expected [$2] to equal [$3]"
    else
      echo -n '.'
    fi
  ;;

  =~ | match )
    if [[ ! "$2" =~ "$3" ]]; then
      echo "FAIL: expected [$2] to match [$3]"
    else
      echo -n '.'
    fi
  ;;

  blank )
    if [[ -n "$2" ]]; then
      echo "FAIL: expected [$2] to be blank"
    else
      echo -n '.'
    fi
  ;;

  *) echo "Unknown operand [$1]"; exit 1

  esac
}

### TEST SUITE ###
echo "$(

  ## SETUP
    source ./pair
    pair ryalnd &> /dev/null

  #1 should set $GIT_AUTHOR_NAME
    pair -q ryalnd
    assert equal "$GIT_AUTHOR_NAME" "Ryland Herrick"

  #2 should set $GIT_AUTHOR_EMAIL
    assert match "$GIT_AUTHOR_EMAIL" "ryalnd"

  #3 should unset $GIT_AUTHOR_NAME
    pair -u &> /dev/null
    assert blank "$GIT_AUTHOR_NAME"

  #4 should unset $GIT_AUTHOR_EMAIL
    pair -u &> /dev/null
    assert blank "$GIT_AUTHOR_EMAIL"

)"
