#!/usr/bin/env bash

# path trickery
  pushd $(dirname $BASH_SOURCE/../scripts) &> /dev/null
  absolute_path=$(pwd -P)
  popd &> /dev/null

usage() {
  echo "
Usage

  setup/pair [action]

Actions
  install - One-time installation of pair
  upgrade - Updates the repo, installs pair if necessary
"
}

get_script() {
  curl -s https://raw.github.com/rylnd/dotfiles/master/scripts/pair > $HOME/.pair
}

symlink_pair() {
  if [[ -e $HOME/.pair ]]; then
    echo "*** Skipping symlink, $HOME/.pair already exists ***"
  else
    ln -s $absolute_path/scripts/pair $HOME/.pair
  fi
}

pair_hook() {
  echo
  echo '# define the pair function'
  echo 'source "$HOME/.pair"'
  echo '# quietly set the previous pairing state'
  echo 'pair -q'
}

modify_dotfile() {
  if ! grep -q "define the pair function" "$HOME/.bash_profile" ; then
    pair_hook >> $HOME/.bash_profile
  else
    echo
    echo "*** Skipping addition of pair hook. ***"
    echo "Previous installation found in $HOME/.bash_profile"
    echo "Please ensure something like the following is there:"
    echo "--------------------------------------"
    pair_hook
    echo "--------------------------------------"
  fi
}

setup_complete() {
  echo
  echo "*** pair is now set up! ***"
  echo "Please source $HOME/.pair or start a new session to use pair."
}

while [[ $# > 0 ]]; do
  arg="$1"
  shift
  case "x$arg" in
    xinstall)
      get_script && modify_dotfile && setup_complete
      ;;
    xupgrade)
      pushd $absolute_path &> /dev/null
      git pull && symlink_pair && modify_dotfile && setup_complete
      popd &> /dev/null
      ;;
    xusage)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done
